spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:file:./data/micro-task;AUTO_SERVER=TRUE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      platform: h2
server:
  port: 8080